### ISSUE TITLE
Documentation Request for classes Property

### ISSUE THREAD

**Issue by g1205610** [JustMaier/angular-autoFields-bootstrap#37]
I tried to build some form with autofields.
However, I'm unable to get the option classes to work.

I created a fiddle to illustrate my problem:
https://jsfiddle.net/NBhn4/106/

Is it a bug with the classes or am I using it wrong?

**Comment by JustMaier** [comment]
@g1205610 It looks like the classes in the options are being applied correctly. What browser are you using?

**Comment by g1205610** [comment]
I'm testing with current Firefox (36.0.4) and current Google Chrome (41.0.2272.118) on a Mac.

The fiddle does not work in Chrome because the URL to the script points to Github and the contents of the file are delivered using text/plain mimetype, not text/javascript. That's because this project seeems to be not available on any CDN i know, so it's difficult to use it in fiddles.

Please note, that I added one field manually to the form. Another field is added using angular-autoFields-bootstrap. The manual field is rendered correctly, the auto field is missing the CSS classes. I did this for better visualization but maybe that idea was not a brilliant one.

Apart from the fiddle, the CSS classes didn't work in my test project in any browser. Could you please have another look at this?

**Comment by JustMaier** [comment]
Hey @g1205610 for testing in plunkr I usually reference the [file hosted on github.io](https://justmaier.github.io/angular-autoFields-bootstrap/autofields.js). Not ideal, I know, I'll submit it for inclusion in cdnjs.

Looks like I wasn't pulling in the directive options when getting the class names. I didn't see this earlier because I generally change the classes globally in the app config (see autofields-bootstrap.js for an example). I've fixed the code and now your [example seems to be working](https://jsfiddle.net/NBhn4/133/).
